spring.application.name=notes-service
spring.profiles.active=${PROFILE_ACTIVE:dev}
server.port=${PORT:7055}
springdoc.writer-with-order-by-keys=true

introspection.uri=${INTROSPECTION_URI:http://localhost:7051/api/v1/auth/introspect}
introspection.client-id=${INTROSPECTION_CLIENT_ID:notes-service}
introspection.client-secret=${INTROSPECTION_CLIENT_SECRET:MyS3cur3Cli3ntS3cr3t!N0tes!}
