spring.main.banner-mode=console
spring.output.ansi.enabled=always

spring.data.mongodb.uri=${MONGODB_URI:mongodb://root:MyS3cur3M0ngoPassw0rd2026!@localhost:7054/notes?authSource=admin}

debug=false
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){blue} %clr(%-5p) %clr([env:${spring.profiles.active}]){green} %clr(${PID}){faint} %clr([%thread]){cyan} %clr(%logger{36}){yellow} %clr(:){red} %clr(%m){faint}%n

server.error.include-path=always
server.error.include-message=always
server.error.include-exception=true
server.error.include-stacktrace=always
server.error.include-binding-errors=always
